AWSTemplateFormatVersion: 2010-09-09
Description: ND9991 C3 L4 
Resources:
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0 
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      GroupDescription: "Test Group"
      SecurityGroups:
        - !Ref SecurityGroup
      KeyName: AWS_EC2_DEMP
      ImageId: 'ami-04505e74c0741db8d' 
      InstanceType: t3.micro
