version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Choose either one of the orbs below
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@2.0.3
# Define the jobs we want to run for this project
jobs:
  create_infrastructure:  # Choose any name, such as `build`
      # The primary container, where your job's commands will run
      executor: aws-cli/default
      steps:
        - checkout # check out the code in the project directory
        - run: 
            name: "Create Cloud Formation Infra"
            command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
                --region $AWS_DEFAULT_REGION
workflows:
  my_workflow:
    jobs:
      - create_infrastructure