# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Use a package of configuration called an orb.
jobs:
  print_hello:
    docker: 
      - image: circleci/node:13.8.0
    steps:
      - run: echo hello
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo world
  print_env_var:
    docker:
      - image: circleci/alpine
    steps:
      - run:
          name: "My env var"
          command: echo $MY_NAME

workflows:
  default:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
      - print_env_var:
          requires:
            - print_world